name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy-static:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build an image
        run: |
          docker build -t gidra39/mlflow-autostop --target=mlflow-autostop .

      - name: Push image
        run: |
            docker tag gidra39/mlflow-autostop:latest
            docker push gidra39/mlflow-autostop:latest